
name: Task Management API CI

on:
  push:
    branches:
      - main
      - feature/task-update-delete
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: task_management
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: 12345678901234567890123456789012

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: temurin
          cache: maven

      - name: Run tests
        run: ./mvnw -B test
